name: beacon_scanner_ios
description: The iOS implementation of beacon_scanner_platform_interface
repository: https://github.com/gfosmbh/beacon_scanner/tree/main/beacon_scanner_ios
version: 0.0.3+1
publish_to: 'none'

environment:
  sdk: '>=3.3.5 <4.0.0'

flutter:
  plugin:
    implements: beacon_scanner
    platforms:
      ios:
        pluginClass: BeaconScannerPlugin
        dartPluginClass: BeaconScannerIOS

dependencies:
  flutter:
    sdk: flutter
  beacon_scanner_platform_interface:
    path: ../beacon_scanner_platform_interface

dependency_overrides:
  collection: ^1.19.0
  material_color_utilities: ^0.12.0