name: beacon_scanner_platform_interface
description: A common platform interface for the beacon_scanner_platform_interface plugin.
repository: https://github.com/gfosmbh/beacon_scanner/tree/main/beacon_scanner_platform_interface
version: 0.0.3

environment:
  sdk: '>=3.3.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  meta: ^1.15.0

dependency_overrides:
  collection: ^1.19.0
  material_color_utilities: ^0.12.0