name: beacon_scanner_android
description: The Android implementation of beacon_scanner_platform_interface
repository: https://github.com/gfosmbh/beacon_scanner/tree/main/beacon_scanner_android
version: 0.0.5
publish_to: 'none'

environment:
  sdk: ">=3.3.5 <4.0.0"
  flutter: ">=3.24.1"

flutter:
  plugin:
    implements: beacon_scanner
    platforms:
      android:
        package: com.lukangagames.plugins.beaconscanner
        pluginClass: BeaconScannerPlugin
        dartPluginClass: BeaconScannerAndroid

dependencies:
  flutter:
    sdk: flutter
  beacon_scanner_platform_interface:
    git:
      url: https://github.com/thorito/beacon_scanner.git
    #path: ../beacon_scanner_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
